[package]
name = "legatio"
version = "0.1.1"
edition = "2021"

[profile.dev]
debug = 1

[profile.dev.package."*"]
debug = false

[dependencies]

# Async runtime
tokio = { version = "1.20.0", features = ["macros"]} # "full"

# Database

sqlx = { version = "0.6.2", features = ["runtime-tokio-native-tls", "sqlite"]} # "macros"

# HTTP client
reqwest = { version = "^0.12.9", default-features = false, features = ["json"] }

# JSON handling
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Environment variable management
dotenv = "0.15"

# Error handling
anyhow = "1.0"

# Logging
log = "0.4"
env_logger = "0.10"

# For calling external commands
async-process = "1.4"

# For managing paths
path-absolutize = "3.0"

# Fzf alternative
skim = "0.9"

# Walk dir
rayon = "1.5"

# uuid
uuid = { version = "1.11.0", features = ["v4"] }

futures = "0.3.31"

# Models
openai-api-rs = "5.2.4"
